# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='contact',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_set1', to='app.User'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_set2', to='app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='frineds',
            field=models.ManyToManyField(related_name='contact_set', through='app.Contact', to='app.User'),
        ),
    ]
