# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171208_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHasTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TagRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='food_type',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant'),
        ),
        migrations.AddField(
            model_name='eventhastag',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
        migrations.AddField(
            model_name='eventhastag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TagEvent'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='TagRestaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TagRestaurant'),
        ),
    ]
